import {
  Anchor,
  AppShell,
  Breadcrumbs,
  Button,
  Card,
  Group,
  Header,
  Stack,
} from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { IconChevronLeft } from "@tabler/icons";
import { useRouter } from "next/router";

const Home: NextPage = ({}) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello
    </>
  );
};

export default Home;
