import type { NextPage } from "next"
import Head from "next/head"
import { trpc } from "../utils/trpc"
import { Stack } from "@mantine/core"
import { createMachine } from "../features/Game/machine"
import { useState } from "react"
import { Map, Robot } from "../features/Game"
import GameVisualizer from "../components/GameVisualizer"

const Home: NextPage = ({}) => {
  const map: Map = {
    cells: [
      { color: "green" },
      { color: "blue", modifier: "button" },
      { color: "blue", modifier: "robot w" },
      { color: "blue", modifier: "barrier" },
      undefined,
      undefined,
      { color: "blue", modifier: "checkpoint" },
      undefined,
      undefined,
    ],
    width: 3,
    height: 3,
  }
  const [robot, setRobot] = useState<Robot>([])

  return (
    <>
      <Head>
        <title>Cooter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Stack>
        <GameVisualizer machine={createMachine({ map, robot })} />
        {/* <RobotEditor robot={robot} setRobot={setRobot} /> */}
      </Stack>
    </>
  )
}

export default Home
